export enum ActionType {
  LOGIN = "LOGIN",
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_ERROR = "LOGIN_ERROR",
  FETCH_USERS_LIST = "FETCH_USERS_LIST",
  USERS_LIST = "USERS_LIST",
  LOGOUT = "LOGOUT",
  LOADING_START = "LOADING_START",
  LOADING_DONE = "LOADING_DONE",
}
